name: Update Code on Push
on:
  push:
    branches:
      - test

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify Code
        run: |
          # Set the file path as an output variable
          echo "::set-output name=file_path::./README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
