name: Copy updated files

# only run this workflow when the openapi file has changed on the master branch
on:
  push:
    branches:
      - test

jobs:
  copy_file_from_One_repository_to_another:
    runs-on: ubuntu-latest
    steps:
      # check out notehub project
      - name: Check out githubActions project
        uses: actions/checkout@v3
      # check out notehub-js project using token generated in that project to successfully access it from inside the Notehub GitHub Action workflow
      - name: Check out testGithub Actions project
        uses: actions/checkout@v3
        with:
          repository: talha12981/testGithubActions
          path: ./testGithubActions
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v3
      - uses: flcdrg/replace-multiple-action@v1
        with:
          files: "../../models/*.lkml"
          find: '[{ "find": "test", "replace": "Main" }]'

      # make a copy the openapi file from notehub project
      - name: Copy OpenAPI file
        run: bash ./.github/scripts/copy_file.sh
        env:
          DESTINATION_PATH: ./testGithubActions/models/

      # make a branch in notehub-js repo and push the copy of the openapi file there
      - name: Push to testGithubActions
        run: bash ./.github/scripts/push_changes.sh
        env:
          BRANCH: main
