name: Update Code on Push
on:
  push:
    branches:
      - test

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        id: changes
        run: |
          echo "::set-output name=changed_files::$(git diff --name-only)"
        shell: bash

      - name: Process Changes
        run: |
          changed_files="${{ steps.changes.outputs.changed_files }}"
          for file in $changed_files; do
            # Pass the file to the index.js script as an argument
            node index.js "$file"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.email "chtalha.anjum@gmail.com"
          git config --global user.name "Talha Anjum"
          git add .
          git commit -m "Updated code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
