name: Update Code on Push
on:
  push:
    branches:
      - test

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify Code
        run: |
          for file in $(git diff --name-only ); do
            
            - name: Set up environment
              env:
                CODE_TO_SEND: |
                  "${{file}}"
        done
      
      - name: Run index.js
          run: node index.js
      - name: Commit and Push Changes
        run: |
          git config --global user.email "chtalha.anjum@gmail.com"
          git config --global user.name "Talha Anjum"
          git add .
          git commit -m "Updated code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
